const wordList = [
    { word: "APPLE", hint: "A fruit that is famously said to keep the doctor away." },
    { word: "BANANA", hint: "A long, yellow fruit that grows in bunches." },
    { word: "COMPUTER", hint: "An electronic device for storing and processing data." },
    { word: "JAVASCRIPT", hint: "A popular programming language for web development." },
    { word: "ELEPHANT", hint: "A very large gray mammal with a trunk." },
    { word: "GUITAR", hint: "A stringed musical instrument with a fretted fingerboard." },
    { word: "MOUNTAIN", hint: "A large natural elevation of the earth's surface." },
    { word: "OCEAN", hint: "A very large expanse of sea." },
    { word: "PIZZA", hint: "A dish of Italian origin, consisting of a flat, round base of dough." },
    { word: "SUNFLOWER", hint: "A tall plant of the daisy family, with large yellow-rayed flowers." },
    { word: "TELESCOPE", hint: "An optical instrument for making distant objects appear larger." },
    { word: "BUTTERFLY", hint: "An insect with two pairs of large wings that are covered with tiny scales." },
    { word: "CHOCOLATE", hint: "A food preparation in the form of a paste or solid block made from roasted and ground cacao seeds." },
    { word: "DIAMOND", hint: "A precious stone consisting of a clear and colorless crystalline form of pure carbon." },
    { word: "FIREWORKS", hint: "A device containing chemicals that causes a spectacular explosion when ignited." },
    { word: "GALAXY", hint: "A system of millions or billions of stars, together with gas and dust." },
    { word: "HOSPITAL", hint: "An institution providing medical and surgical treatment for sick or injured people." },
    { word: "LIBRARY", hint: "A building containing collections of books and other media for public use." },
    { word: "MICROSCOPE", hint: "An optical instrument used for viewing very small objects." },
    { word: "VOLCANO", hint: "A mountain or hill with a crater through which lava erupts." },
    { word: "BRIDGE", hint: "A structure built to span a physical obstacle like a river or road." },
    { word: "PYRAMID", hint: "A monumental structure with a square base and triangular sides." },
    { word: "ROBOT", hint: "A machine capable of carrying out complex actions automatically." },
    { word: "CANDLE", hint: "A stick of wax with a central wick that is lit to produce light." },
    { word: "ZEBRA", hint: "A striped African wild horse." },
    { word: "BICYCLE", hint: "A two-wheeled vehicle powered by pedaling." },
    { word: "LANTERN", hint: "A portable light source with a protective enclosure." },
    { word: "RAINBOW", hint: "A multicolored arc in the sky caused by refraction of sunlight." },
    { word: "CASTLE", hint: "A large fortified building from the medieval period." },
    { word: "BRUSH", hint: "A tool with bristles used for cleaning or painting." },
    { word: "PLANET", hint: "A celestial body orbiting a star." },
    { word: "TRAIN", hint: "A series of connected vehicles that run along a track." },
    { word: "WHALE", hint: "A very large marine mammal." },
    { word: "KANGAROO", hint: "A marsupial native to Australia." },
    { word: "BRICKS", hint: "Rectangular blocks used for building walls." },
    { word: "BREAD", hint: "A food made of flour, water, and yeast." },
    { word: "CLOCK", hint: "A device for measuring and indicating time." },
    { word: "CHAIR", hint: "A piece of furniture for sitting." },
    { word: "TABLE", hint: "A piece of furniture with a flat top and legs." },
    { word: "CLOUD", hint: "A visible mass of condensed water vapor in the sky." },
    { word: "DOOR", hint: "A hinged or sliding barrier for entry or exit." },
    { word: "WINDOW", hint: "An opening in a wall fitted with glass." },
    { word: "BOTTLE", hint: "A container with a narrow neck for liquids." },
    { word: "PENCIL", hint: "An instrument for writing or drawing." },
    { word: "MARKER", hint: "A pen with a thick tip for marking surfaces." },
    { word: "PAPER", hint: "Material manufactured in thin sheets for writing or printing." },
    { word: "BOOK", hint: "A set of written or printed pages bound together." },
    { word: "PHONE", hint: "A device used to communicate over long distances." },
    { word: "CAMERA", hint: "A device used to capture photographs or videos." },
    { word: "SHOES", hint: "Footwear to protect and comfort the feet." },
    { word: "JACKET", hint: "A piece of clothing worn on the upper body." },
    { word: "HAT", hint: "A covering for the head, often worn for protection or style." },
    { word: "GLOVES", hint: "Hand coverings with separate sections for each finger." },
    { word: "SOCKS", hint: "Garments worn on the feet under shoes." },
    { word: "BAG", hint: "A container used for carrying items." },
    { word: "LADDER", hint: "A structure for climbing up or down." },
    { word: "RULER", hint: "A straight-edged tool for measuring length." },
    { word: "SCISSORS", hint: "A cutting instrument with two blades." },
    { word: "MAP", hint: "A representation of an area of land or sea." },
    { word: "GLOBE", hint: "A spherical representation of Earth." },
    { word: "CAR", hint: "A four-wheeled motor vehicle for transporting people." },
    { word: "TRUCK", hint: "A motor vehicle for transporting goods." },
    { word: "BUS", hint: "A large motor vehicle carrying passengers." },
    { word: "PLANE", hint: "A powered flying vehicle with fixed wings." },
    { word: "SHIP", hint: "A large boat used for travel or transport over water." },
    { word: "SUBMARINE", hint: "A watercraft capable of underwater operation." },
    { word: "ROCKET", hint: "A vehicle designed to travel through space." },
    { word: "BALLOON", hint: "A flexible bag inflated with gas or air." },
    { word: "KITE", hint: "A lightweight object flown in the wind on a string." },
    { word: "DRUM", hint: "A percussion instrument played by striking." },
    { word: "FLUTE", hint: "A wind instrument with holes along its body." },
    { word: "PIANO", hint: "A large musical instrument with a keyboard." },
    { word: "VIOLIN", hint: "A string instrument played with a bow." },
    { word: "TRUMPET", hint: "A brass wind instrument with valves." },
    { word: "HARP", hint: "A large stringed musical instrument." },
    { word: "BANJO", hint: "A string instrument with a round body." },
    { word: "CYMBALS", hint: "Percussion instruments made of metal plates." },
    { word: "XYLOPHONE", hint: "A percussion instrument with wooden bars." },
    { word: "SAXOPHONE", hint: "A woodwind instrument made of brass." },
    { word: "TAMBORINE", hint: "A percussion instrument with jingles." },
    { word: "MARACAS", hint: "A percussion instrument shaken to produce sound." },
    { word: "WHISTLE", hint: "A small device that makes a high sound when air is blown into it." },
    { word: "ANCHOR", hint: "A heavy device dropped into water to hold a ship in place." },
    { word: "CHAIN", hint: "A series of connected metal links." },
    { word: "LOCK", hint: "A device used to secure something." },
    { word: "KEY", hint: "A small piece of shaped metal used to open locks." },
    { word: "COIN", hint: "A flat, typically round piece of metal used as money." },
    { word: "WALLET", hint: "A small folding case for carrying money." },
    { word: "PURSE", hint: "A small bag used for carrying money and personal items." },
    { word: "BELT", hint: "A strip of material worn around the waist." },
    { word: "BUTTON", hint: "A small fastener for clothing." },
    { word: "ZIPPER", hint: "A fastening device made of interlocking metal or plastic teeth." },
    { word: "NECKLACE", hint: "A piece of jewelry worn around the neck." },
    { word: "BRACELET", hint: "A piece of jewelry worn around the wrist." },
    { word: "RING", hint: "A small circular band worn on a finger." },
    { word: "EARRINGS", hint: "Jewelry worn on the ears." },
    { word: "MIRROR", hint: "A reflective surface, typically glass coated with metal." },
    { word: "STARGAZING", hint: "Observing the stars in the night sky." },
    { word: "THUNDERSTORM", hint: "A storm with thunder and lightning." },
    { word: "BASKETBALL", hint: "A sport played with a ball and a hoop." },
    { word: "MOTORCYCLE", hint: "A two-wheeled motor vehicle." },
    { word: "SNOWFLAKE", hint: "A single ice crystal that has fallen from the sky." },
    { word: "FRIENDSHIP", hint: "A close relationship between friends." },
    { word: "SPACESHIP", hint: "A vehicle designed for travel in outer space." },
    { word: "EARTHQUAKE", hint: "A sudden shaking of the ground." },
    { word: "SCHOOLBAG", hint: "A bag used to carry books to school." },
    { word: "PINEAPPLE", hint: "A tropical fruit with spiky skin." },
    { word: "HEADPHONES", hint: "A device worn over the ears to listen to audio." },
    { word: "SANDWICH", hint: "Food consisting of two pieces of bread with filling between them." },
    { word: "NOTEBOOK", hint: "A book of blank pages for writing notes." },
    { word: "SUNSET", hint: "The daily disappearance of the sun below the horizon." },
    { word: "CUPCAKE", hint: "A small cake designed for one person." },
    { word: "PAINTBRUSH", hint: "A brush used for applying paint." },
    { word: "DRAGONFLY", hint: "An insect with a long body and two pairs of wings." },
    { word: "CANDLELIGHT", hint: "Light produced by a candle." },
    { word: "GOLDFISH", hint: "A small golden-colored fish kept as a pet." },
    { word: "WHEELCHAIR", hint: "A chair with wheels used by people who cannot walk." },
    { word: "LIGHTHOUSE", hint: "A tower with a light to guide ships at sea." },
    { word: "FOOTPRINT", hint: "A mark left by a foot on a surface." },
    { word: "RAINDROP", hint: "A single drop of rain." },
    { word: "MUSHROOM", hint: "A fungus with a round cap on a stalk." },
    { word: "TOOTHBRUSH", hint: "A brush used for cleaning teeth." },
    { word: "BACKPACK", hint: "A bag carried on the back." },
    { word: "DOORSTEP", hint: "A step in front of a door." },
    { word: "SUNSCREEN", hint: "Lotion applied to protect the skin from the sun." },
    { word: "KEYBOARD", hint: "A set of keys for typing on a computer." },
    { word: "SPAGHETTI", hint: "A type of Italian pasta." },
    { word: "PENCILCASE", hint: "A container for holding pencils." },
    { word: "LADDER", hint: "A structure for climbing up or down." },
    { word: "BICYCLE", hint: "A vehicle with two wheels powered by pedaling." },
    { word: "CARPET", hint: "A thick floor covering." },
    { word: "UMBRELLA", hint: "A device used for protection from rain." },
    { word: "TREASURE", hint: "Valuable items such as gold, jewels, or money." },
    { word: "DINOSAUR", hint: "An extinct reptile that lived millions of years ago." },
    { word: "SANDCASTLE", hint: "A castle built from sand." },
    { word: "EARRINGS", hint: "Jewelry worn on the ears." },
    { word: "BLANKET", hint: "A large piece of fabric used for warmth." },
    { word: "AIRPLANE", hint: "A powered flying vehicle with wings." },
    { word: "RAINBOW", hint: "A multicolored arc in the sky after rain." },
    { word: "NECKLACE", hint: "Jewelry worn around the neck." },
    { word: "BOOKMARK", hint: "A marker used to keep track of reading progress." },
    { word: "FIREPLACE", hint: "A structure for containing a fire indoors." },
    { word: "WATERFALL", hint: "Water flowing over the edge of a cliff." },
    { word: "SNOWMAN", hint: "A figure made of snow." },
    { word: "COCONUT", hint: "A tropical fruit with a hard shell." },
    { word: "PLAYGROUND", hint: "An outdoor area for children to play." },
    { word: "TENTACLE", hint: "A flexible limb found on some sea creatures." },
    { word: "ICEBERG", hint: "A large floating mass of ice." },
    { word: "PASSPORT", hint: "An official document for traveling abroad." },
    { word: "MOONLIGHT", hint: "Light from the moon." },
    { word: "SHIPWRECK", hint: "A wrecked or destroyed ship." },
    { word: "SUITCASE", hint: "A case for carrying clothes while traveling." },
    { word: "PENGUIN", hint: "A flightless bird that lives in cold climates." },
    { word: "SPIDERWEB", hint: "A web made by a spider." },
    { word: "FIRETRUCK", hint: "A vehicle used for fighting fires." },
    { word: "POTATOES", hint: "A starchy vegetable grown underground." },
    { word: "TURTLE", hint: "A reptile with a hard shell." },
    { word: "WATERMELON", hint: "A large green fruit with red flesh." },
    { word: "SEASHORE", hint: "The land along the edge of the sea." },
    { word: "CUPBOARD", hint: "A cabinet with shelves for storing items." },
    { word: "SOAPBUBBLE", hint: "A bubble formed from soap film." },
    { word: "SNOWBOARD", hint: "A board used for sliding down snowy slopes." },
    { word: "PENCIL", hint: "A writing instrument made of graphite and wood." },
    { word: "SCISSORS", hint: "A tool with two blades for cutting." },
    { word: "BREAD", hint: "A baked food made from flour and water." },
    { word: "MIRROR", hint: "A reflective surface." },
    { word: "BELL", hint: "A hollow object that rings when struck." },
    { word: "LEMONADE", hint: "A drink made from lemon juice, water, and sugar." },
    { word: "CLOUD", hint: "A visible mass of condensed water vapor in the sky." },
    { word: "SHOELACE", hint: "A lace for fastening shoes." },
    { word: "KITE", hint: "A toy flown in the wind at the end of a string." },
    { word: "ROCKET", hint: "A vehicle propelled by engines, used in space travel." },
    { word: "FORK", hint: "A utensil with prongs used for eating." },
    { word: "CANDLE", hint: "A stick of wax with a wick for burning." },
    { word: "GLOBE", hint: "A spherical representation of Earth." },
    { word: "SHELL", hint: "A hard outer covering of some animals." },
    { word: "CHALK", hint: "A soft white rock used for writing or drawing." },
    { word: "PILLOW", hint: "A soft cushion for resting your head." },
    { word: "CHAIR", hint: "A piece of furniture for sitting." },
    { word: "CLOCK", hint: "A device for measuring time." },
    { word: "HAT", hint: "A head covering worn for style or protection." },
    { word: "GUITARIST", hint: "A person who plays the guitar." },
    { word: "ACTOR", hint: "A person who performs in plays or movies." },
    { word: "DOCTOR", hint: "A person qualified to treat the sick." },
    { word: "PAINTER", hint: "An artist who applies paint to a surface." },
    { word: "TEACHER", hint: "A person who educates students." },
    { word: "DANCER", hint: "A person who dances." },
    { word: "SINGER", hint: "A person who sings." },
    { word: "BAKER", hint: "A person who bakes bread and cakes." },
    { word: "CHEF", hint: "A professional cook." },
    { word: "FARMER", hint: "A person who cultivates land or raises animals." },
    { word: "ALGORITHM", hint: "A step-by-step procedure for solving a problem or accomplishing a task." },
    { word: "BACTERIA", hint: "Microscopic single-celled organisms that can be found everywhere." },
    { word: "CARNIVAL", hint: "A public event with music, dancing, and processions." },
    { word: "DINOSAUR", hint: "An extinct reptile that lived millions of years ago." },
    { word: "ELEVATOR", hint: "A machine used for carrying people or goods between different floors." },
    { word: "FIREFIGHTER", hint: "A person trained to put out fires." },
    { word: "GLACIER", hint: "A large mass of ice that moves slowly over land." },
    { word: "HEADPHONES", hint: "A pair of speakers worn over or in the ears." },
    { word: "ILLUSION", hint: "A deceptive appearance or impression." },
    { word: "JOURNAL", hint: "A daily record of news and events of a personal nature." },
    { word: "KEYBOARD", hint: "An input device used to type on a computer." },
    { word: "LABYRINTH", hint: "A complicated irregular network of passages or paths." },
    { word: "MAGNETIC", hint: "Capable of being attracted by a magnet." },
    { word: "NEBULA", hint: "A cloud of gas and dust in outer space." },
    { word: "ORCHESTRA", hint: "A large group of musicians playing together." },
    { word: "PANTHER", hint: "A large wild cat known for its dark fur." },
    { word: "QUICKSAND", hint: "Loose wet sand that gives way under weight." },
    { word: "RAINDROP", hint: "A single drop of rain." },
    { word: "SATELLITE", hint: "An object placed in orbit around the Earth or another planet." },
    { word: "TAPESTRY", hint: "A piece of thick textile fabric with pictures or designs." },
    { word: "UMBRELLA", hint: "A device used for protection against rain or sun." },
    { word: "VULTURE", hint: "A large bird of prey feeding mainly on carrion." },
    { word: "WHIRLPOOL", hint: "A rapidly rotating mass of water." },
    { word: "XYLOPHONE", hint: "A musical instrument with wooden bars struck by mallets." },
    { word: "YAWNING", hint: "Opening the mouth wide and taking a deep breath involuntarily." },
    { word: "ZUCCHINI", hint: "A green variety of smooth-skinned summer squash." },
    { word: "ANCHOR", hint: "A heavy object used to keep a ship in place." },
    { word: "BALCONY", hint: "A platform enclosed by a wall or railing projecting from a building." },
    { word: "CANDLE", hint: "A stick of wax with a central wick that burns to give light." },
    { word: "DRAGON", hint: "A mythical monster resembling a giant reptile." },
    { word: "ENVELOPE", hint: "A flat paper container used to enclose a letter." },
    { word: "FEATHER", hint: "A covering on the body of a bird." },
    { word: "GIRAFFE", hint: "A tall African mammal with a very long neck." },
    { word: "HAMMER", hint: "A tool with a heavy metal head used for pounding nails." },
    { word: "ICEBERG", hint: "A large floating mass of ice detached from a glacier." },
    { word: "JACKET", hint: "An outer garment extending either to the waist or the hips." },
    { word: "KANGAROO", hint: "A large Australian marsupial with strong legs for hopping." },
    { word: "LADDER", hint: "A structure for climbing, consisting of two side pieces and rungs." },
    { word: "MARBLE", hint: "A type of stone or a small glass ball used as a toy." },
    { word: "NEEDLE", hint: "A small, slender instrument for sewing." },
    { word: "OXYGEN", hint: "A chemical element essential for breathing." },
    { word: "PENGUIN", hint: "A flightless bird that lives in cold climates." },
    { word: "QUILL", hint: "A pen made from a bird's feather." },
    { word: "RABBIT", hint: "A small burrowing mammal with long ears." },
    { word: "SPIDER", hint: "An eight-legged arachnid that spins webs." },
    { word: "TORNADO", hint: "A rapidly rotating column of air in contact with the ground." },
    { word: "UNICORN", hint: "A mythical horse-like creature with a single horn." },
    { word: "VIOLIN", hint: "A stringed instrument played with a bow." },
    { word: "WINDOW", hint: "An opening in the wall or roof of a building that is fitted with glass." },
    { word: "XENON", hint: "A colorless, dense, odorless noble gas." },
    { word: "YACHT", hint: "A medium-sized sailboat equipped for cruising or racing." },
    { word: "ZIPPER", hint: "A device used for fastening clothes, bags, or other items." },
    { word: "ASTRONAUT", hint: "A person trained to travel in a spacecraft." },
    { word: "BRIDGE", hint: "A structure carrying a road or path across a river or gap." },
    { word: "CASTLE", hint: "A large fortified building or set of buildings." },
    { word: "DESERT", hint: "A barren area of landscape with little rainfall." },
    { word: "EAGLE", hint: "A large bird of prey with a hooked beak." },
    { word: "FOREST", hint: "A large area covered chiefly with trees and undergrowth." },
    { word: "GUITARIST", hint: "A person who plays the guitar." },
    { word: "HONEYBEE", hint: "A bee that collects nectar and produces honey." },
    { word: "ISLAND", hint: "A piece of land surrounded by water." },
    { word: "JUNGLE", hint: "An area of dense forest and tangled vegetation." },
    { word: "KOALA", hint: "An Australian marsupial with large ears and a spoon-shaped nose." },
    { word: "LANTERN", hint: "A lamp with a transparent case to protect the flame or bulb." },
    { word: "MONKEY", hint: "A primate with a long tail and dexterous hands." },
    { word: "NEST", hint: "A structure built by birds for laying eggs." },
    { word: "OCTOPUS", hint: "A sea creature with eight arms." },
    { word: "PARROT", hint: "A colorful bird known for imitating sounds." },
    { word: "QUARTZ", hint: "A hard mineral composed of silica." },
    { word: "ROBOT", hint: "A machine capable of carrying out complex tasks automatically." },
    { word: "SNAKE", hint: "A long, legless reptile." },
    { word: "TIGER", hint: "A large wild cat with a striped coat." },
    { word: "URANIUM", hint: "A heavy metal used as fuel in nuclear reactors." },
    { word: "VILLAGE", hint: "A small group of houses in a rural area." },
    { word: "WHALE", hint: "A very large marine mammal." },
    { word: "XYLEM", hint: "Plant tissue that conducts water." },
    { word: "YOGURT", hint: "A dairy product produced by bacterial fermentation of milk." },
    { word: "ZEBRA", hint: "An African wild horse with black-and-white stripes." },
    { word: "ANTENNA", hint: "A device for transmitting or receiving radio waves." },
    { word: "BICYCLE", hint: "A two-wheeled vehicle powered by pedaling." },
    { word: "CLOUD", hint: "A visible mass of condensed water vapor floating in the atmosphere." },
    { word: "DRUM", hint: "A percussion instrument sounded by being struck." },
    { word: "ENGINE", hint: "A machine designed to convert energy into useful work." },
    { word: "FROG", hint: "A tailless amphibian with a short squat body." },
    { word: "GLOBE", hint: "A spherical model of Earth." },
    { word: "HARP", hint: "A large stringed musical instrument." },
    { word: "IGLOO", hint: "A dome-shaped Eskimo house built from blocks of snow." },
    { word: "JELLYFISH", hint: "A free-swimming marine coelenterate with a gelatinous umbrella-shaped body." },
    { word: "KITE", hint: "A toy consisting of a light frame with thin material stretched over it, flown in the wind." },
    { word: "LION", hint: "A large carnivorous feline known as the king of the jungle." },
    { word: "MAP", hint: "A representation of an area showing physical features." },
    { word: "NIGHT", hint: "The time from sunset to sunrise." },
    { word: "OWL", hint: "A nocturnal bird of prey with large eyes." },
    { word: "PLANE", hint: "A powered flying vehicle with fixed wings." },
    { word: "QUIZ", hint: "A test of knowledge." },
    { word: "RING", hint: "A small circular band worn on a finger." },
    { word: "SUN", hint: "The star at the center of our solar system." },
    { word: "TREE", hint: "A perennial plant with an elongated stem or trunk." },
    { word: "URCHIN", hint: "A small spiny marine animal." },
    { word: "VASE", hint: "An open container for holding flowers." },
    { word: "WIND", hint: "The movement of air from high to low pressure areas." },
    { word: "XRAY", hint: "An image produced by X-rays." },
    { word: "YARN", hint: "Spun thread used for knitting or weaving." },
    { word: "ZONE", hint: "An area with a particular characteristic or purpose." },
    { word: "PENGUIN", hint: "A flightless bird found in the Southern Hemisphere." },
    { word: "PIANIST", hint: "A person who plays the piano." },
    { word: "PRISONER", hint: "A person who is kept in a prison." },
    { word: "PYRAMID", hint: "A monumental structure with a square or triangular base and sloping sides." },
    { word: "RAINDROP", hint: "A single drop of rain." },
    { word: "RANSOM", hint: "Money demanded for the release of a captive." },
    { word: "RAZOR", hint: "A tool used for shaving hair." },
    { word: "RECIPE", hint: "Instructions for preparing a dish." },
    { word: "REFUGEE", hint: "A person forced to leave their country to escape danger." },
    { word: "RELAY", hint: "A race in which team members take turns running parts of the distance." },
    { word: "RELIC", hint: "An object surviving from an earlier time, especially of historical interest." },
    { word: "REMEDY", hint: "A medicine or treatment for a disease or injury." },
    { word: "RENOVATE", hint: "To restore something to a good condition." },
    { word: "REPTILE", hint: "A cold-blooded vertebrate like snakes or lizards." },
    { word: "RESCUE", hint: "To save someone from danger or distress." },
    { word: "RESERVOIR", hint: "A large natural or artificial lake used to store water." },
    { word: "RESIGN", hint: "To voluntarily leave a job or position." },
    { word: "REUNION", hint: "A gathering of people who have been apart." },
    { word: "REVENGE", hint: "The action of inflicting harm in return for a wrong." },
    { word: "REWRITE", hint: "To write something again with changes." },
    { word: "RHINOCEROS", hint: "A large, heavy animal with one or two horns on its nose." },
    { word: "RHYTHM", hint: "A strong, repeated pattern of sound or movement." },
    { word: "RIPPLE", hint: "A small wave on the surface of water." },
    { word: "ROBOT", hint: "A machine capable of carrying out tasks automatically." },
    { word: "ROCKET", hint: "A missile or vehicle propelled by engines." },
    { word: "ROGUE", hint: "A dishonest or unprincipled person." },
    { word: "ROLLER", hint: "A cylindrical object used to flatten or shape things." },
    { word: "ROMANCE", hint: "A love story." },
    { word: "ROSTER", hint: "A list of names or tasks." },
    { word: "ROUTINE", hint: "A sequence of actions regularly followed." },
    { word: "RUBBLE", hint: "Broken stone or bricks from destroyed buildings." },
    { word: "RUCKSACK", hint: "A bag carried on the back, often by hikers." },
    { word: "RULER", hint: "A tool used to measure length." },
    { word: "RUMOR", hint: "A circulating story of uncertain truth." },
    { word: "RUNWAY", hint: "A strip where airplanes take off and land." },
    { word: "SADDLE", hint: "A seat fastened on a horse's back." },
    { word: "SAFARI", hint: "An expedition to observe animals in their natural habitat." },
    { word: "SAILOR", hint: "A person who works on a ship or boat." },
    { word: "SALAD", hint: "A cold dish of vegetables or fruits." },
    { word: "SALMON", hint: "A pink-fleshed fish popular in cooking." },
    { word: "SALOON", hint: "A public room or bar." },
    { word: "SAMPLE", hint: "A small part used to represent the whole." },
    { word: "SANDAL", hint: "A light open shoe." },
    { word: "SANDBOX", hint: "A shallow box filled with sand for children to play in." },
    { word: "SANDWICH", hint: "Food made of bread with a filling between." },
    { word: "SATELLITE", hint: "An object that orbits a planet." },
    { word: "SAVANNA", hint: "A grassy plain in tropical or subtropical regions." },
    { word: "SAVIOR", hint: "A person who saves someone from danger." },
    { word: "SAXOPHONE", hint: "A brass musical instrument." },
    { word: "SCARF", hint: "A piece of fabric worn around the neck." },
    { word: "SCHOOL", hint: "A place where children are educated." },
    { word: "SCIENCE", hint: "The study of the natural world." },
    { word: "SCISSORS", hint: "A tool for cutting paper or cloth." },
    { word: "SCOOTER", hint: "A two-wheeled vehicle powered by a motor or foot." },
    { word: "SCRATCH", hint: "To scrape or rub with nails or claws." },
    { word: "SCREWDRIVER", hint: "A tool for turning screws." },
    { word: "SCROLL", hint: "A rolled-up sheet of paper or parchment." },
    { word: "SCULPTURE", hint: "A three-dimensional art piece." },
    { word: "SEAGULL", hint: "A type of seabird with white and gray feathers." },
    { word: "SEASON", hint: "One of the four divisions of the year." },
    { word: "SEEDLING", hint: "A young plant just starting to grow." },
    { word: "SEISMIC", hint: "Relating to earthquakes." },
    { word: "SELFIE", hint: "A photograph taken of oneself." },
    { word: "SENATOR", hint: "A member of a legislative body." },
    { word: "SENTRY", hint: "A guard who watches for danger." },
    { word: "SERPENT", hint: "A large snake." },
    { word: "SERVICE", hint: "The action of helping or doing work for someone." },
    { word: "SHACKLE", hint: "A restraint for the wrists or ankles." },
    { word: "SHADOW", hint: "A dark area caused by blocking light." },
    { word: "SHAFT", hint: "A long, narrow part of an object." },
    { word: "SHALLOW", hint: "Not deep." },
    { word: "SHAMPOO", hint: "A liquid used to wash hair." },
    { word: "SHARK", hint: "A large predatory fish." },
    { word: "SHEARS", hint: "Large scissors for cutting plants or cloth." },
    { word: "SHEEP", hint: "A domesticated animal kept for wool and meat." },
    { word: "SHELTER", hint: "A place that provides protection from the weather." },
    { word: "SHERIFF", hint: "An elected law enforcement officer." },
    { word: "SHIELD", hint: "A protective device used to block attacks." },
    { word: "SHIFT", hint: "To move or change position." },
    { word: "SHIVER", hint: "To shake slightly from cold or fear." },
    { word: "SHOVEL", hint: "A tool with a broad blade for digging." },
    { word: "SHRIMP", hint: "A small marine crustacean." },
    { word: "SHRINE", hint: "A place regarded as holy." },
    { word: "SHRUB", hint: "A woody plant smaller than a tree." },
    { word: "SHUTTLE", hint: "A vehicle that travels back and forth regularly." },
    { word: "SIBLING", hint: "A brother or sister." },
    { word: "SIGNAL", hint: "A gesture or sound used to convey a message." },
    { word: "SILENCE", hint: "The absence of sound." },
    { word: "SILVER", hint: "A shiny gray precious metal." },
    { word: "SIMMER", hint: "To cook just below boiling point." },
    { word: "SINGER", hint: "A person who sings." },
    { word: "SINKHOLE", hint: "A depression in the ground caused by collapse." },
    { word: "SKATEBOARD", hint: "A short board on wheels ridden standing up." },
    { word: "SKELETON", hint: "The framework of bones in a body." },
    { word: "SKETCH", hint: "A rough or unfinished drawing." },
    { word: "SKIING", hint: "The sport of gliding over snow on skis." },
    { word: "SPONGE", hint: "A porous material used for cleaning." },
    { word: "SUGAR", hint: "A sweet crystalline substance obtained from plants." },
    { word: "TELEPHONE", hint: "A device for voice communication over distances." },
    { word: "TRAFFIC", hint: "The movement of vehicles along a road." },
    { word: "VACUUM", hint: "A space entirely devoid of matter." },
    { word: "WAGON", hint: "A four-wheeled vehicle for transporting goods." },
    { word: "WHISTLE", hint: "A device that produces a shrill sound when air is blown through it." },
    { word: "WINDOW", hint: "An opening in a wall to let in light or air." },
    { word: "ANCHOR", hint: "A device used to moor a vessel to the sea bottom." },
    { word: "ANTLER", hint: "The branched horns of a deer." },
    { word: "BLOSSOM", hint: "A flower or a mass of flowers on a tree or bush." },
    { word: "BRIDGE", hint: "A structure carrying a road or path across a river or gap." },
    { word: "BROOM", hint: "A brush with a long handle for sweeping." },
    { word: "BUBBLE", hint: "A thin sphere of liquid enclosing air or another gas." },
    { word: "CANDLE", hint: "A block of wax with a wick for burning to provide light." },
    { word: "CASTLE", hint: "A large building fortified against attack." },
    { word: "CHAIN", hint: "A series of linked metal rings." },
    { word: "CLOVER", hint: "A small plant with three-lobed leaves." },
    { word: "CLOWN", hint: "A comic entertainer in a circus." },
    { word: "CLOUD", hint: "A visible mass of condensed water vapor in the sky." },
    { word: "COAST", hint: "The part of the land near the sea." },
    { word: "CORAL", hint: "A hard stony substance formed by the skeletons of marine organisms." },
    { word: "CRAYON", hint: "A stick of colored wax used for drawing." },
    { word: "DAISY", hint: "A small grassland plant with white petals and a yellow center." },
    { word: "DEW", hint: "Tiny drops of water on cool surfaces in the morning." },
    { word: "DOLPHIN", hint: "A small, intelligent marine mammal." },
    { word: "DRAGON", hint: "A mythical monster like a giant reptile." },
    { word: "DRUM", hint: "A percussion instrument played by beating with sticks or hands." },
    { word: "EAGLE", hint: "A large bird of prey with a massive hooked bill." },
    { word: "FAIRY", hint: "A mythical being of folklore and romance." },
    { word: "FEATHER", hint: "One of the flat appendages growing from a bird’s skin." },
    { word: "FERRY", hint: "A boat or ship for conveying passengers and goods." },
    { word: "FISHING", hint: "The activity of catching fish." },
    { word: "FLAME", hint: "A hot glowing body of ignited gas." },
    { word: "FLOOD", hint: "An overflow of a large amount of water." },
    { word: "FLOUR", hint: "A powder obtained by grinding grain." },
    { word: "FOSSIL", hint: "The remains of a prehistoric organism preserved in rock." },
    { word: "FROG", hint: "A small tailless amphibian with long legs." },
    { word: "FURNACE", hint: "An enclosed structure for heating." },
    { word: "GARLIC", hint: "A strong-smelling bulb used as flavoring in cooking." },
    { word: "GEAR", hint: "A toothed wheel that engages with another to transmit motion." },
    { word: "GHOST", hint: "A spirit of a dead person." },
    { word: "GIANT", hint: "A mythical being of superhuman size." },
    { word: "GLOBE", hint: "A spherical model of Earth." },
    { word: "GNOME", hint: "A mythical dwarf-like creature." },
    { word: "GOOSE", hint: "A large waterbird with a long neck." },
    { word: "GRAPE", hint: "A small round fruit growing in clusters on vines." },
    { word: "GRASS", hint: "Vegetation consisting of typically short plants." },
    { word: "GRAVE", hint: "A place of burial." },
    { word: "HAIL", hint: "Pellets of frozen rain falling from clouds." },
    { word: "HAMMER", hint: "A tool with a heavy metal head used for driving nails." },
    { word: "HARP", hint: "A stringed musical instrument played by plucking." },
    { word: "HAWK", hint: "A bird of prey with broad rounded wings." },
    { word: "HIVE", hint: "A structure where bees live." },
    { word: "HONEY", hint: "A sweet substance made by bees." },
    { word: "HORN", hint: "A hard permanent outgrowth on the head of some animals." },
    { word: "HURRICANE", hint: "A storm with violent wind." },
    { word: "ICEBERG", hint: "A large floating mass of ice detached from a glacier." },
    { word: "IGLOO", hint: "A dome-shaped Eskimo house made of blocks of snow." },
    { word: "INK", hint: "A colored fluid used for writing or printing." },
    { word: "IVY", hint: "A climbing evergreen plant." },
    { word: "JELLY", hint: "A sweet fruit-flavored dessert set with gelatin." },
    { word: "JUNGLE", hint: "An area of dense forest and tangled vegetation." },
    { word: "KITE", hint: "A toy flown in the wind at the end of a string." },
    { word: "KITTEN", hint: "A young cat." },
    { word: "KNIGHT", hint: "A man awarded a non-hereditary title of honor by a monarch." },
    { word: "LADDER", hint: "A device used for climbing up or down." },
    { word: "LAGOON", hint: "A stretch of salt water separated from the sea." },
    { word: "LAMB", hint: "A young sheep." },
    { word: "LANTERN", hint: "A lamp with a transparent case." },
    { word: "LEAF", hint: "A flat green part of a plant." },
    { word: "LEMON", hint: "A yellow citrus fruit." },
    { word: "LIZARD", hint: "A reptile with a long body and tail." },
    { word: "LOAF", hint: "A quantity of bread shaped and baked in one piece." },
    { word: "LOCK", hint: "A device for securing a door, lid, etc." },
    { word: "LOG", hint: "A part of the trunk or a large branch of a tree." },
    { word: "LOTUS", hint: "A plant with large, showy flowers." },
    { word: "LUTE", hint: "A stringed instrument with a long neck." },
    { word: "MAGNET", hint: "A piece of material that attracts iron." },
    { word: "MAPLE", hint: "A type of tree known for its distinctive leaves." },
    { word: "MARBLE", hint: "A metamorphic rock used in sculpture and architecture." },
    { word: "MERMAID", hint: "A mythical sea creature with the head and upper body of a woman and the tail of a fish." },
    { word: "MIRROR", hint: "A reflective surface." },
    { word: "MOON", hint: "Earth's natural satellite." },
    { word: "MOSS", hint: "A small green plant growing in damp conditions." },
    { word: "MOTH", hint: "An insect similar to a butterfly but usually active at night." },
    { word: "MOUSE", hint: "A small rodent." },
    { word: "MUG", hint: "A large cup, typically cylindrical with a handle." },
    { word: "NAIL", hint: "A small metal spike used to fasten things together." },
    { word: "NEEDLE", hint: "A slender pointed tool used for sewing." },
    { word: "NET", hint: "A mesh material used for catching fish or other animals." },
    { word: "NEST", hint: "A structure built by birds to hold eggs." },
    { word: "NUT", hint: "A fruit composed of a hard shell and a seed." },
    { word: "OAK", hint: "A large tree that bears acorns." },
    { word: "OASIS", hint: "A fertile spot in a desert where water is found." },
    { word: "OAT", hint: "A cereal plant cultivated for its grain." },
    { word: "OIL", hint: "A viscous liquid derived from petroleum or plants." },
    { word: "ONION", hint: "An edible bulb used in cooking." }


];

export default wordList;
